"""v0.5: pgvector extension, documents and chunks

Hand-written rather than autogenerated: Alembic cannot express CREATE EXTENSION,
and the `vector` column type is not part of SQLAlchemy's core types.

The HNSW index is created here for correctness, but note the operational rule in
docs/10-rag-architecture.md: on a large corpus, build the index AFTER loading,
because inserting into an existing HNSW index is markedly slower than building it
over existing rows.
"""

from alembic import op
import sqlalchemy as sa

revision = "5a881f4bdb98"
down_revision = "e25051359e64"
branch_labels = None
depends_on = None

DIMENSIONS = 1536


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("metadata", sa.dialects.postgresql.JSONB(), nullable=False,
                  server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("content_hash", name="documents_content_hash_unique"),
    )
    op.create_index("idx_documents_source", "documents", ["source"])

    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("heading", sa.String(length=500), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("metadata", sa.dialects.postgresql.JSONB(), nullable=False,
                  server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"), ondelete="CASCADE",
        ),
        sa.UniqueConstraint("document_id", "chunk_index", name="chunks_document_index_unique"),
    )
    # The vector column, added separately: SQLAlchemy core has no `vector` type.
    op.execute(f"ALTER TABLE chunks ADD COLUMN embedding vector({DIMENSIONS})")

    # HNSW with cosine ops. The query MUST use the matching `<=>` operator, or
    # Postgres silently falls back to a sequential scan.
    op.execute(
        "CREATE INDEX idx_chunks_embedding ON chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_index("idx_chunks_document", "chunks", ["document_id"])


def downgrade() -> None:
    op.drop_index("idx_chunks_document", table_name="chunks")
    op.execute("DROP INDEX IF EXISTS idx_chunks_embedding")
    op.drop_table("chunks")
    op.drop_index("idx_documents_source", table_name="documents")
    op.drop_table("documents")
    # The extension is deliberately NOT dropped: other things may depend on it,
    # and dropping an extension is not the inverse of this migration's purpose.
